DROP DATABASE IF EXISTS mynode_db;
CREATE DATABASE mynode_db;
USE mynode_db;
CREATE TABLE classes (areaOfStudy VARCHAR(255), department VARCHAR(255), id INT, classname VARCHAR(255), credithours INT,  PRIMARY KEY (id, areaOfStudy));
INSERT INTO classes VALUES ('Theoretical Computer Science & Programming Languages', 'CSCI', 5101, 'Analysis of Algorithms', 3);
INSERT INTO classes VALUES ('Theoretical Computer Science & Programming Languages', 'CSCI', 5501,'Programming Language Structure', 3);
INSERT INTO classes VALUES ('Theoretical Computer Science & Programming Languages', 'CSCI', 6101, 'Theory of Algorithms and their Complexity', 3);
INSERT INTO classes VALUES ('Theoretical Computer Science & Programming Languages', 'CSCI', 6110, 'Applied Combinatorics and Graph Theory', 3);
INSERT INTO classes VALUES ('Theoretical Computer Science & Programming Languages', 'CSCI', 6120, 'Theory of Computation', 3);
INSERT INTO classes VALUES ('Theoretical Computer Science & Programming Languages', 'CSCI', 6140, 'Formal Languages', 3);
INSERT INTO classes VALUES ('Systems & Network', 'CSCI', 5401, 'Principles of Operating Systems I', 3);
INSERT INTO classes VALUES ('Systems & Network', 'CSCI', 5311, 'Computer Networks and Telecommunications', 3);
INSERT INTO classes VALUES ('Systems & Network', 'CSCI', 5460, 'Network Operation and Defense', 3);
INSERT INTO classes VALUES ('Systems & Network', 'CSCI', 6401, 'Concurrent Programming', 3);
INSERT INTO classes VALUES ('Systems & Network', 'CSCI', 6450, 'Principles of Distributed Systems', 3);
INSERT INTO classes VALUES ('Systems & Network', 'CSCI', 6452, 'Cloud Computing', 3);
INSERT INTO classes VALUES ('Systems & Network', 'CSCI', 6454, 'Parallel and Scientific Computing', 3);
INSERT INTO classes VALUES ('Systems & Network', 'CSCI', 6621, 'Topics in Network Security and Forensics', 3);
INSERT INTO classes VALUES ('Systems & Network', 'CSCI', 6625, 'Network Penetration Testing and Defense', 3);
INSERT INTO classes VALUES ('Software Systems', 'CSCI', 5208, 'Developing Advanced Web Applications', 3);
INSERT INTO classes VALUES ('Software Systems', 'CSCI', 5210, 'Introduction to Software Engineering;', 3);
INSERT INTO classes VALUES ('Software Systems', 'CSCI', 6220, 'Software Testing and Quality Assurance', 3);
INSERT INTO classes VALUES ('Software Systems', 'CSCI', 6350, 'Development of Distributed Software', 3);
INSERT INTO classes VALUES ('Software Systems', 'CSCI', 6363, 'Agile Software Engineering', 3);
INSERT INTO classes VALUES ('Software Systems', 'CSCI', 6603, 'Programming Language Security', 3);
INSERT INTO classes VALUES ('Software Systems', 'CSCI', 6663, 'Software Security', 3);
INSERT INTO classes VALUES ('Cybersecurity', 'CSCI', 5130, 'Introduction to Cryptography', 3);
INSERT INTO classes VALUES ('Cybersecurity', 'CSCI', 5460, 'Network Operation and Defense', 3);
INSERT INTO classes VALUES ('Cybersecurity', 'CSCI', 5621, 'Intro to Cyber Security', 3);
INSERT INTO classes VALUES ('Cybersecurity', 'CSCI', 5622, 'Software Reverse Engineering', 3);
INSERT INTO classes VALUES ('Cybersecurity', 'CSCI', 5623, 'Digital Forensics', 3);
INSERT INTO classes VALUES ('Cybersecurity', 'CSCI', 6621, 'Topics in Network Security and Forensics', 3);
INSERT INTO classes VALUES ('Cybersecurity', 'CSCI', 6627, 'Industrial Control System', 3);
INSERT INTO classes VALUES ('Cybersecurity', 'CSCI', 6663, 'Software Security', 3);
INSERT INTO classes VALUES ('Cybersecurity', 'CSCI', 6625, 'Network Penetration Testing and Defense', 3);
INSERT INTO classes VALUES ('Database Systems & Distributed Applications', 'CSCI', 5125, 'Data Models and Database Systems', 3);
INSERT INTO classes VALUES ('Database Systems & Distributed Applications', 'CSCI', 5661, 'Topics in Mobile Applications Development', 3);
INSERT INTO classes VALUES ('Database Systems & Distributed Applications', 'CSCI', 6250, 'Big Data Analytics and Systems', 3);
INSERT INTO classes VALUES ('Database Systems & Distributed Applications', 'CSCI', 6350, 'Development of Distributed Software', 3);
INSERT INTO classes VALUES ('Database Systems & Distributed Applications', 'CSCI', 6454, 'Parallel and Scientific Computing', 3);
INSERT INTO classes VALUES ('Computer Graphics & Visual Computing', 'CSCI', 5631, 'Principles of Computer Graphics', 3);
INSERT INTO classes VALUES ('Computer Graphics & Visual Computing', 'CSCI', 5632, 'Principles of Image Processing', 3);
INSERT INTO classes VALUES ('Computer Graphics & Visual Computing', 'CSCI', 6454, 'Parallel and Scientific Computing', 3);
INSERT INTO classes VALUES ('Computer Graphics & Visual Computing', 'CSCI', 6633, 'Computer Vision', 3);
INSERT INTO classes VALUES ('Computer Graphics & Visual Computing', 'CSCI', 6634, 'Data Visualization', 3);
INSERT INTO classes VALUES ('Computer Graphics & Visual Computing', 'CSCI', 6640, 'Computational Geometry', 3);
INSERT INTO classes VALUES ('Artificial Intelligence', 'CSCI', 5525, 'Introduction to Artifical Intelligence', 3);	
INSERT INTO classes VALUES ('Artificial Intelligence', 'CSCI', 5567, 'Bioinformatics I', 3);
INSERT INTO classes VALUES ('Artificial Intelligence', 'CSCI', 5568, 'Bioinformatics II', 3);
INSERT INTO classes VALUES ('Artificial Intelligence', 'CSCI', 5587, 'Machine Learning I', 3);
INSERT INTO classes VALUES ('Artificial Intelligence', 'CSCI', 5588, 'Machine Learning II', 3);
INSERT INTO classes VALUES ('Artificial Intelligence', 'CSCI', 5595, 'Topics in Bioinformatics', 3);
INSERT INTO classes VALUES ('Artificial Intelligence', 'CSCI', 5588, 'Machine Learning Methods in Bioinformatics II', 3);
INSERT INTO classes VALUES ('Artificial Intelligence', 'CSCI', 5670, 'Fundamentals of Game Development', 3);
INSERT INTO classes VALUES ('Artificial Intelligence', 'CSCI', 5675, 'Advanced Game Development', 3);
INSERT INTO classes VALUES ('Artificial Intelligence', 'CSCI', 6454, 'Parallel and Scientific Computing', 3);
INSERT INTO classes VALUES ('Artificial Intelligence', 'CSCI', 6521, 'Advanced Maching Learning I', 3);
INSERT INTO classes VALUES ('Artificial Intelligence', 'CSCI', 6522, 'Advanced Machine Learning II', 3);
INSERT INTO classes VALUES ('Artificial Intelligence', 'CSCI', 6587, 'Advanced Machine Learning in Bioinformatics I', 3);
INSERT INTO classes VALUES ('Artificial Intelligence', 'CSCI', 6588, 'Advanced Machine Learning in Bioinformatics II', 3);
INSERT INTO classes VALUES ('Artificial Intelligence', 'CSCI', 6595, 'Advanced Topics in Bioinformatics', 3);
INSERT INTO classes VALUES ('Artificial Intelligence', 'CSCI', 6635, 'Theory & Applications for Pattern Recognition', 3);
INSERT INTO classes VALUES ('Artificial Intelligence', 'CSCI', 6645, 'Planning Algorithms in Artificial Intelligence', 3);
INSERT INTO classes VALUES ('Artificial Intelligence', 'CSCI', 6650, 'Intelligent Agents and Multi-Agent Systems', 3);

